/* Registers the book's own units (PISA.bookUnits, generated by
 * tools/import_book.py) as on-screen units: one screen per question, with
 * the question and its answer controls on the left and the unit's stimulus
 * on the right, as on the PISA platform. Scoring comes from
 * js/units/book_scoring.js.
 *
 * The PISA tasks of the Grade 9 textbook «គណិតវិទ្យាថ្នាក់ទី៩ បែបទំនើប»
 * (PISA.textbookUnits, generated by the website build) use the same screens.
 * Their text keeps the book's mathematics as TeX, drawn by KaTeX; a question
 * is scored automatically only when the book's answer names the right option,
 * otherwise the teacher marks it.
 */
(function () {
  'use strict';
  const { h, W } = PISA;
  const KM_DIGIT = /[០-៩]+/;
  const plain = (html) => String(html || '').replace(/<br>/g, ' ').replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();

  // Part names, in the order the blocks appear (see book_scoring.js).
  function partsOf(blocks) {
    const parts = [];
    let a = 0, x = 0, w = 0;
    blocks.forEach((b) => {
      if (b.type === 'options') parts.push({ k: b.key || 'opt', b });
      else if (b.type === 'filltable') b.rows.forEach((row) => row.forEach((c) => { if (c.input) parts.push({ k: c.input, b }); }));
      else if (b.type === 'choice') b.rows.forEach((_, i) => parts.push({ k: String(i), b, row: i }));
      else if (b.type === 'answer') parts.push({ k: 'a' + (++a), b });
      else if (b.type === 'essay') parts.push({ k: w++ ? 'why' + w : 'why', b });
      else if (b.type === 'line') parts.push({ k: 'x' + (++x), b });
      else if (b.type === 'grid') gridCells(b).forEach((c) => parts.push({ k: c.k, b }));
    });
    return parts;
  }
  function gridCells(b) {
    const cells = [];
    b.rows.forEach((row) => {
      const m = KM_DIGIT.exec(row.label);
      if (!m) return;
      const rn = PISA.latin(m[0]);
      row.cells.forEach((c, i) => { if (!c) cells.push({ k: 'g' + rn + '-' + (i + 1), row: rn, col: i + 1 }); });
    });
    return cells;
  }

  // ------------------------------------------------------------ blocks ---
  function tableNode(b, cls) {
    const t = h('table', { class: cls || 'dtable' });
    if (b.head.length) {
      const th = h('thead');
      b.head.forEach((row) => th.append(h('tr', {}, ...row.map((c) => h('th', { colspan: c.span > 1 ? c.span : null, html: c.html })))));
      t.append(th);
    }
    const tb = h('tbody');
    b.body.forEach((row) => tb.append(h('tr', {}, ...row.map((c) => h('td', { colspan: c.span > 1 ? c.span : null, html: c.html })))));
    t.append(tb);
    return h('div', { class: 'dtable-wrap' }, t);
  }

  // Fill-in grid (unit ដ): empty cells cycle blank → ក → ខ when clicked.
  function gridNode(ctx, qid, b) {
    const t = h('table', { class: 'fillgrid' });
    const tb = h('tbody');
    b.rows.forEach((row) => {
      const m = KM_DIGIT.exec(row.label);
      const tr = h('tr', {}, h('th', { class: 'rl', html: row.label }));
      row.cells.forEach((c, i) => {
        if (!m) { tr.append(h('td', { class: 'cl', html: c })); return; }
        if (c) { tr.append(h('td', { class: 'given', html: c })); return; }
        const k = 'g' + PISA.latin(m[0]) + '-' + (i + 1);
        const btn = h('button', { type: 'button', class: 'cyc', 'aria-label': plain(row.label) + ' ជួរឈរ ' + (i + 1) });
        const show = () => { btn.textContent = ctx.val(qid, k) || ''; btn.classList.toggle('filled', !!ctx.val(qid, k)); };
        btn.addEventListener('click', () => {
          const order = ['', 'ក', 'ខ'];
          const next = order[(order.indexOf(ctx.val(qid, k) || '') + 1) % order.length];
          ctx.setVal(qid, k, next || null);
          show();
        });
        show();
        tr.append(h('td', { class: 'resp' }, btn));
      });
      tb.append(tr);
    });
    t.append(tb);
    return h('div', { class: 'stack' }, t, h('p', { class: 'hint' }, 'ចុចលើប្រអប់ទទេ ដើម្បីដាក់ ក ចុចម្ដងទៀតដើម្បីប្ដូរជា ខ ហើយចុចម្ដងទៀតដើម្បីលុប។'));
  }

  // Table with cells to type in (the textbook's "fill in the table" questions).
  function fillTableNode(ctx, qid, b, math) {
    const t = h('table', { class: 'dtable fill' });
    t.append(h('thead', {}, h('tr', {}, ...b.head.map((c) => h('th', { html: c.html })))));
    const tb = h('tbody');
    b.rows.forEach((row, ri) => tb.append(h('tr', {}, ...row.map((c, ci) => (c.input
      ? h('td', { class: 'resp' }, W.input(ctx, qid, c.input, '', { cls: 'cell-in', math, label: plain((row[0] || {}).html) + ' — ' + plain((b.head[ci] || {}).html) }))
      : h('td', { html: c.html }))))));
    t.append(tb);
    return h('div', { class: 'dtable-wrap' }, t);
  }

  function renderBlocks(ctx, qid, blocks, opts) {
    const box = h('div', { class: 'stack book' });
    const parts = qid ? partsOf(blocks) : [];
    const partFor = (b) => parts.filter((p) => p.b === b);
    blocks.forEach((b) => {
      switch (b.type) {
        case 'p': box.append(W.p(b.html)); break;
        case 'html': box.append(h('div', { class: 'bhtml', html: b.html })); break;
        case 'filltable': box.append(fillTableNode(ctx, qid, b, opts.math)); break;
        case 'quote': box.append(h('blockquote', { class: 'bq', html: b.html })); break;
        case 'list': box.append(h(b.ordered ? 'ol' : 'ul', {}, ...b.items.map((x) => h('li', { html: x })))); break;
        case 'dmath': box.append(h('p', { class: 'dm' }, h('span', { class: 'm', html: b.html }))); break;
        case 'note': box.append(h('p', { class: 'fignote', html: b.html })); break;
        case 'table': box.append(tableNode(b, b.sep ? 'dtable sep' : 'dtable')); break;
        case 'figure': box.append(h('div', { class: 'bfig' }, h('img', { src: b.src, alt: 'រូបភាព' }))); break;
        case 'options':
          box.append(W.radios(ctx, qid, b.key || 'opt', b.opts.map((o) => ({
            v: o.v, html: (o.letter ? '<span class="olet">' + o.letter + '.</span> ' : '') + o.html,
          })), { cls: b.style === 'box' ? 'boxes' : '' }));
          break;
        case 'choice':
          box.append(W.choiceTable(ctx, qid, {
            head: b.head, rows: b.rows,
            cols: b.cols.map((c, i) => ({ v: String(i), html: c, label: plain(c) })),
          }));
          break;
        case 'answer': {
          const k = partFor(b)[0].k;
          box.append(h('div', { class: 'ansline' },
            b.pre ? h('span', { class: 'pre', html: b.pre }) : null,
            W.input(ctx, qid, k, '', { cls: 'ans', math: opts.math, label: plain(b.pre) || 'ចម្លើយ' }),
            b.post ? h('span', { class: 'post', html: b.post }) : null));
          if (opts.workBox && !box.querySelector('.work')) {
            box.append(h('div', { class: 'work' }, h('p', { class: 'small' }, 'វិធីគណនា៖'), W.textarea(ctx, qid, 'work', 'សូមសរសេរវិធីគណនារបស់អ្នកនៅទីនេះ', 4)));
          }
          break;
        }
        case 'essay':
          box.append(h('div', { class: 'essay' }, h('p', { html: b.label }), W.textarea(ctx, qid, partFor(b)[0].k, 'សូមវាយចម្លើយនៅទីនេះ', 5)));
          break;
        case 'line': {
          const k = partFor(b)[0].k;
          box.append(h('div', { class: 'ansline wide' }, h('span', { class: 'pre', html: b.label }), W.input(ctx, qid, k, '', { cls: 'ans', math: opts.math, label: plain(b.label) })));
          break;
        }
        case 'grid': box.append(gridNode(ctx, qid, b)); break;
        default: break;
      }
    });
    return box;
  }
  PISA.renderBookBlocks = renderBlocks;

  // ----------------------------------------------------------- summary ---
  function summaryOf(q, r, workBox) {
    const out = [];
    partsOf(q.blocks).forEach((p) => {
      const v = r[p.k];
      const b = p.b;
      if (b.type === 'options') {
        const o = b.opts.find((x) => x.v === v);
        out.push(o ? (o.letter ? o.letter + '. ' : '') + plain(o.html) : '—');
      } else if (b.type === 'choice') {
        out.push(PISA.km(p.row + 1) + '. ' + (v != null ? plain(b.cols[Number(v)]) : '—'));
      } else if (b.type === 'answer') {
        out.push((plain(b.pre) ? plain(b.pre) + ' ' : '') + (v || '—') + (plain(b.post) ? ' ' + plain(b.post) : ''));
      } else if (b.type === 'filltable') {
        out.push(v || '—');
      } else if (b.type === 'essay' || b.type === 'line') {
        out.push((b.type === 'line' ? plain(b.label) + ' ' : '') + (v || '—'));
      }
    });
    const grid = q.blocks.find((b) => b.type === 'grid');
    if (grid) {
      const byRow = {};
      gridCells(grid).forEach((c) => { (byRow[c.row] = byRow[c.row] || []).push(r[c.k] || '_'); });
      Object.keys(byRow).sort().reverse().forEach((row) => out.push('ជួរដេកទី ' + PISA.km(row) + '៖ ' + byRow[row].join(' ')));
    }
    if (workBox) out.push('វិធីគណនា៖ ' + (r.work || '—'));
    return out.join(' | ');
  }

  function formatOf(q) {
    if (q.spec && q.spec.format) return 'សំណួរ' + q.spec.format;
    return '';
  }

  // ---------------------------------------------------------- register ---
  const FOOTER = 'សំណួរដើមរបស់គម្រោង តាមបែប PISA — មិនមែនជាសំណួរផ្លូវការរបស់ OECD ឬ PISA ទេ';
  const TEXTBOOK_FOOTER = '«គណិតវិទ្យាថ្នាក់ទី៩ បែបទំនើប» © លោកគ្រូ សាន សុខលី — លំហាត់តាមបែប PISA មិនមែនជាសំណួរផ្លូវការរបស់ OECD ឬ PISA ទេ';
  const NO_KEY = '<p class="knote">សៀវភៅមិនទាន់មានចម្លើយគំរូសម្រាប់សំណួរនេះទេ — គ្រូជាអ្នកដាក់ពិន្ទុ។</p>';
  // Textbook tasks: the right option scores; with more to answer, the teacher reads the rest.
  const autoRule = (q, parts) => (r) => {
    if (r.opt !== q.auto) return { pts: 0, note: r.opt ? 'ជម្រើសមិនត្រឹមត្រូវ' : 'មិនបានជ្រើសរើស' };
    return parts.length > 1 ? { pts: null, note: 'ជម្រើសត្រឹមត្រូវ — គ្រូត្រូវអានផ្នែកផ្សេងទៀត' } : { pts: q.points };
  };

  function register(u) {
    const textbook = u.kind === 'textbook';
    const questions = {};
    const screens = [];
    const stimulus = (ctx) => h('div', { class: 'stack' },
      u.stimTitle ? h('div', { class: 'stim-title', html: u.stimTitle }) : null,
      renderBlocks(ctx, null, u.stimulus, {}));
    u.questions.forEach((q) => {
      const qid = u.id + 'q' + q.no;
      const workBox = !!PISA.bookWorkBox[qid];
      const parts = partsOf(q.blocks).map((p) => ({ k: p.k }));
      const spec = q.spec ? '<p class="knote">' + [
        q.spec.process ? 'ដំណើរការ៖ ' + q.spec.process : '',
        q.spec.level ? 'កម្រិតប៉ាន់ស្មាន៖ ' + q.spec.level : '',
      ].filter(Boolean).join(' · ') + ' (ការប៉ាន់ស្មានរបស់អ្នករៀបរៀង មិនមែនការក្រិតតាមខ្នាតផ្លូវការរបស់ PISA)</p>' : '';
      questions[qid] = {
        label: 'សំណួរ ' + PISA.km(q.no),
        format: formatOf(q),
        max: q.points,
        process: q.spec && q.spec.process,
        level: q.spec && q.spec.level,
        parts,
        summary: (r) => summaryOf(q, r, workBox),
        score: PISA.bookScoring[qid] || (q.auto ? autoRule(q, parts) : () => ({ pts: null })),
        key: textbook ? (q.key || NO_KEY) : q.key + spec,
      };
      const hasWide = q.blocks.some((b) => b.type === 'figure' || b.type === 'grid' || b.type === 'table' || b.type === 'filltable');
      screens.push({
        tag: 'សំណួរ ' + PISA.km(q.no) + ' / ' + PISA.km(u.questions.length),
        split: hasWide ? 52 : 45,
        items: [qid],
        left: (ctx) => renderBlocks(ctx, qid, q.blocks, { workBox, math: textbook }),
        right: stimulus,
      });
    });
    PISA.registerUnit({
      id: u.id,
      no: u.code,
      code: u.code,
      collection: u.kind,
      grade: u.grade,
      title: u.title,
      en: u.kind === 'gold' ? u.code : textbook ? 'Textbook task ' + PISA.latin(u.code) : 'Practice ' + u.code,
      label: u.kind === 'gold' ? u.code : textbook ? 'លំហាត់ ' + u.code : 'ប្រធានបទ ' + u.code,
      blurb: textbook ? 'មេរៀនទី ' + PISA.km(u.lesson) + ' ' + u.lessonTitle : plain(u.stimTitle),
      lesson: u.lesson,
      lessonTitle: u.lessonTitle,
      note: u.note,
      footer: textbook ? TEXTBOOK_FOOTER : FOOTER,
      lessonUrl: u.lessonUrl,
      questions,
      screens,
    });
  }
  (PISA.bookUnits || []).forEach(register);
  (PISA.textbookUnits || []).forEach(register);
})();
